/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacybeleidRouteImport } from './routes/privacybeleid'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as NalatenschapsmediationRouteImport } from './routes/nalatenschapsmediation'
import { Route as NalatenschapscheckRouteImport } from './routes/nalatenschapscheck'
import { Route as KennisbankRouteImport } from './routes/kennisbank'
import { Route as HulpBijErfenisRouteImport } from './routes/hulp-bij-erfenis'
import { Route as GratisGidsRouteImport } from './routes/gratis-gids'
import { Route as ExecuteurschapRouteImport } from './routes/executeurschap'
import { Route as ErfbelastingAangifteRouteImport } from './routes/erfbelasting-aangifte'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BijLevenRegelenRouteImport } from './routes/bij-leven-regelen'
import { Route as BedanktRouteImport } from './routes/bedankt'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KennisbankSlugRouteImport } from './routes/kennisbank.$slug'

const PrivacybeleidRoute = PrivacybeleidRouteImport.update({
  id: '/privacybeleid',
  path: '/privacybeleid',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const NalatenschapsmediationRoute = NalatenschapsmediationRouteImport.update({
  id: '/nalatenschapsmediation',
  path: '/nalatenschapsmediation',
  getParentRoute: () => rootRouteImport,
} as any)
const NalatenschapscheckRoute = NalatenschapscheckRouteImport.update({
  id: '/nalatenschapscheck',
  path: '/nalatenschapscheck',
  getParentRoute: () => rootRouteImport,
} as any)
const KennisbankRoute = KennisbankRouteImport.update({
  id: '/kennisbank',
  path: '/kennisbank',
  getParentRoute: () => rootRouteImport,
} as any)
const HulpBijErfenisRoute = HulpBijErfenisRouteImport.update({
  id: '/hulp-bij-erfenis',
  path: '/hulp-bij-erfenis',
  getParentRoute: () => rootRouteImport,
} as any)
const GratisGidsRoute = GratisGidsRouteImport.update({
  id: '/gratis-gids',
  path: '/gratis-gids',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecuteurschapRoute = ExecuteurschapRouteImport.update({
  id: '/executeurschap',
  path: '/executeurschap',
  getParentRoute: () => rootRouteImport,
} as any)
const ErfbelastingAangifteRoute = ErfbelastingAangifteRouteImport.update({
  id: '/erfbelasting-aangifte',
  path: '/erfbelasting-aangifte',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BijLevenRegelenRoute = BijLevenRegelenRouteImport.update({
  id: '/bij-leven-regelen',
  path: '/bij-leven-regelen',
  getParentRoute: () => rootRouteImport,
} as any)
const BedanktRoute = BedanktRouteImport.update({
  id: '/bedankt',
  path: '/bedankt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KennisbankSlugRoute = KennisbankSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KennisbankRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bedankt': typeof BedanktRoute
  '/bij-leven-regelen': typeof BijLevenRegelenRoute
  '/contact': typeof ContactRoute
  '/erfbelasting-aangifte': typeof ErfbelastingAangifteRoute
  '/executeurschap': typeof ExecuteurschapRoute
  '/gratis-gids': typeof GratisGidsRoute
  '/hulp-bij-erfenis': typeof HulpBijErfenisRoute
  '/kennisbank': typeof KennisbankRouteWithChildren
  '/nalatenschapscheck': typeof NalatenschapscheckRoute
  '/nalatenschapsmediation': typeof NalatenschapsmediationRoute
  '/over-ons': typeof OverOnsRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/kennisbank/$slug': typeof KennisbankSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bedankt': typeof BedanktRoute
  '/bij-leven-regelen': typeof BijLevenRegelenRoute
  '/contact': typeof ContactRoute
  '/erfbelasting-aangifte': typeof ErfbelastingAangifteRoute
  '/executeurschap': typeof ExecuteurschapRoute
  '/gratis-gids': typeof GratisGidsRoute
  '/hulp-bij-erfenis': typeof HulpBijErfenisRoute
  '/kennisbank': typeof KennisbankRouteWithChildren
  '/nalatenschapscheck': typeof NalatenschapscheckRoute
  '/nalatenschapsmediation': typeof NalatenschapsmediationRoute
  '/over-ons': typeof OverOnsRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/kennisbank/$slug': typeof KennisbankSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bedankt': typeof BedanktRoute
  '/bij-leven-regelen': typeof BijLevenRegelenRoute
  '/contact': typeof ContactRoute
  '/erfbelasting-aangifte': typeof ErfbelastingAangifteRoute
  '/executeurschap': typeof ExecuteurschapRoute
  '/gratis-gids': typeof GratisGidsRoute
  '/hulp-bij-erfenis': typeof HulpBijErfenisRoute
  '/kennisbank': typeof KennisbankRouteWithChildren
  '/nalatenschapscheck': typeof NalatenschapscheckRoute
  '/nalatenschapsmediation': typeof NalatenschapsmediationRoute
  '/over-ons': typeof OverOnsRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/kennisbank/$slug': typeof KennisbankSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bedankt'
    | '/bij-leven-regelen'
    | '/contact'
    | '/erfbelasting-aangifte'
    | '/executeurschap'
    | '/gratis-gids'
    | '/hulp-bij-erfenis'
    | '/kennisbank'
    | '/nalatenschapscheck'
    | '/nalatenschapsmediation'
    | '/over-ons'
    | '/privacybeleid'
    | '/kennisbank/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bedankt'
    | '/bij-leven-regelen'
    | '/contact'
    | '/erfbelasting-aangifte'
    | '/executeurschap'
    | '/gratis-gids'
    | '/hulp-bij-erfenis'
    | '/kennisbank'
    | '/nalatenschapscheck'
    | '/nalatenschapsmediation'
    | '/over-ons'
    | '/privacybeleid'
    | '/kennisbank/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bedankt'
    | '/bij-leven-regelen'
    | '/contact'
    | '/erfbelasting-aangifte'
    | '/executeurschap'
    | '/gratis-gids'
    | '/hulp-bij-erfenis'
    | '/kennisbank'
    | '/nalatenschapscheck'
    | '/nalatenschapsmediation'
    | '/over-ons'
    | '/privacybeleid'
    | '/kennisbank/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BedanktRoute: typeof BedanktRoute
  BijLevenRegelenRoute: typeof BijLevenRegelenRoute
  ContactRoute: typeof ContactRoute
  ErfbelastingAangifteRoute: typeof ErfbelastingAangifteRoute
  ExecuteurschapRoute: typeof ExecuteurschapRoute
  GratisGidsRoute: typeof GratisGidsRoute
  HulpBijErfenisRoute: typeof HulpBijErfenisRoute
  KennisbankRoute: typeof KennisbankRouteWithChildren
  NalatenschapscheckRoute: typeof NalatenschapscheckRoute
  NalatenschapsmediationRoute: typeof NalatenschapsmediationRoute
  OverOnsRoute: typeof OverOnsRoute
  PrivacybeleidRoute: typeof PrivacybeleidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacybeleid': {
      id: '/privacybeleid'
      path: '/privacybeleid'
      fullPath: '/privacybeleid'
      preLoaderRoute: typeof PrivacybeleidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nalatenschapsmediation': {
      id: '/nalatenschapsmediation'
      path: '/nalatenschapsmediation'
      fullPath: '/nalatenschapsmediation'
      preLoaderRoute: typeof NalatenschapsmediationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nalatenschapscheck': {
      id: '/nalatenschapscheck'
      path: '/nalatenschapscheck'
      fullPath: '/nalatenschapscheck'
      preLoaderRoute: typeof NalatenschapscheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kennisbank': {
      id: '/kennisbank'
      path: '/kennisbank'
      fullPath: '/kennisbank'
      preLoaderRoute: typeof KennisbankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hulp-bij-erfenis': {
      id: '/hulp-bij-erfenis'
      path: '/hulp-bij-erfenis'
      fullPath: '/hulp-bij-erfenis'
      preLoaderRoute: typeof HulpBijErfenisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gratis-gids': {
      id: '/gratis-gids'
      path: '/gratis-gids'
      fullPath: '/gratis-gids'
      preLoaderRoute: typeof GratisGidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executeurschap': {
      id: '/executeurschap'
      path: '/executeurschap'
      fullPath: '/executeurschap'
      preLoaderRoute: typeof ExecuteurschapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erfbelasting-aangifte': {
      id: '/erfbelasting-aangifte'
      path: '/erfbelasting-aangifte'
      fullPath: '/erfbelasting-aangifte'
      preLoaderRoute: typeof ErfbelastingAangifteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bij-leven-regelen': {
      id: '/bij-leven-regelen'
      path: '/bij-leven-regelen'
      fullPath: '/bij-leven-regelen'
      preLoaderRoute: typeof BijLevenRegelenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bedankt': {
      id: '/bedankt'
      path: '/bedankt'
      fullPath: '/bedankt'
      preLoaderRoute: typeof BedanktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kennisbank/$slug': {
      id: '/kennisbank/$slug'
      path: '/$slug'
      fullPath: '/kennisbank/$slug'
      preLoaderRoute: typeof KennisbankSlugRouteImport
      parentRoute: typeof KennisbankRoute
    }
  }
}

interface KennisbankRouteChildren {
  KennisbankSlugRoute: typeof KennisbankSlugRoute
}

const KennisbankRouteChildren: KennisbankRouteChildren = {
  KennisbankSlugRoute: KennisbankSlugRoute,
}

const KennisbankRouteWithChildren = KennisbankRoute._addFileChildren(
  KennisbankRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BedanktRoute: BedanktRoute,
  BijLevenRegelenRoute: BijLevenRegelenRoute,
  ContactRoute: ContactRoute,
  ErfbelastingAangifteRoute: ErfbelastingAangifteRoute,
  ExecuteurschapRoute: ExecuteurschapRoute,
  GratisGidsRoute: GratisGidsRoute,
  HulpBijErfenisRoute: HulpBijErfenisRoute,
  KennisbankRoute: KennisbankRouteWithChildren,
  NalatenschapscheckRoute: NalatenschapscheckRoute,
  NalatenschapsmediationRoute: NalatenschapsmediationRoute,
  OverOnsRoute: OverOnsRoute,
  PrivacybeleidRoute: PrivacybeleidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
